ALTER TABLE `giocatorino`.`boardgame_designer` 
CHANGE COLUMN `DESIGNER_NAME` `DESIGNER_NAME` VARCHAR(75) NOT NULL ;


ALTER TABLE `giocatorino`.`boardgame_status` 
DROP FOREIGN KEY `DEMONSTRATORID`;
ALTER TABLE `giocatorino`.`boardgame_status` 
CHANGE COLUMN `DEMONSTRATOR` `DEMONSTRATOR` INT(11) NULL DEFAULT 0 ;
ALTER TABLE `giocatorino`.`boardgame_status` 
ADD CONSTRAINT `DEMONSTRATORID`
  FOREIGN KEY (`DEMONSTRATOR`)
  REFERENCES `giocatorino`.`users` (`USERID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;