ALTER TABLE `giocatorino`.`boardgame_status` 
CHANGE COLUMN `NOTES` `ID_EXIT` TINYINT(2) NULL DEFAULT NULL ;

ALTER TABLE `giocatorino`.`boardgame_status` 
ADD COLUMN `LANGUAGE` VARCHAR(45) NULL AFTER `ID_EXIT`,
ADD COLUMN `ID_MAINGAME` INT(11) NOT NULL AFTER `LANGUAGE`;


ALTER TABLE `giocatorino`.`boardgame_status` 
ADD COLUMN `DEMONSTRATOR` INT(11) NULL AFTER `ID_MAINGAME`,
ADD INDEX `DEMONSTRATORID_idx` (`DEMONSTRATOR` ASC);
ALTER TABLE `giocatorino`.`boardgame_status` 
ADD CONSTRAINT `DEMONSTRATORID`
  FOREIGN KEY (`DEMONSTRATOR`)
  REFERENCES `giocatorino`.`users` (`USERID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
UPDATE `giocatorino`.`boardgame_status` SET `ID_EXIT`=0;
ALTER TABLE `giocatorino`.`boardgame_status` 
CHANGE COLUMN `ID_EXIT` `ID_EXIT` TINYINT(2) NULL DEFAULT 0 ;
