CREATE TABLE `giocatorino`.`boardgame_catogory` (
  `ID_CATEGORY` INT NOT NULL,
  `CATEGORY_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_CATEGORY`),
  INDEX `CATEGORY_INDEX` (`CATEGORY_NAME`(6) ASC));
  
CREATE TABLE `giocatorino`.`category_fkey` (
  `ID_GAME` INT(11) NOT NULL,
  `ID_CATEGORY` INT(11) NOT NULL,
  UNIQUE INDEX `CATEGORYKEY` (`ID_GAME` ASC, `ID_CATEGORY` ASC),
  INDEX `CATEGORY_ID_idx` (`ID_CATEGORY` ASC),
  CONSTRAINT `CATEGORY_ID`
    FOREIGN KEY (`ID_CATEGORY`)
    REFERENCES `giocatorino`.`boardgame_catogory` (`ID_CATEGORY`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CATEGORY_ID_GAME`
    FOREIGN KEY (`ID_GAME`)
    REFERENCES `giocatorino`.`boardgames` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
